### ISSUE TITLE
Small typo, it should be ClickOnMyWishlist()

### ISSUE THREAD

**Issue by horgaemilia** [pitpalac36/Testing-Internship#101]
https://github.com/pitpalac36/Testing-Internship/blob/dc18beb111b0ab20d1bcf82a04a4c6a8e8024c2b/Madison/Pages/MyWishlistPage.cs#L33

**Comment by pitpalac36** [comment]
https://github.com/pitpalac36/Testing-Internship/commit/fce593f35696c5ebdf96e2bc388671668d5d95a5
