### ISSUE TITLE
we usually don't add try catch blocks in test methods. we want  to hide every implementation detail in page classes. the tests must be clean and should contain only the step that a user should do

### ISSUE THREAD

**Issue by ramonaZmole** [pitpalac36/Testing-Internship#11]
https://github.com/pitpalac36/Testing-Internship/blob/bc1d4f455f8334de374fe623cf04de835f8db7c0/Madison/Tests/TestCart.cs#L38

**Comment by horgaemilia** [comment]
https://github.com/pitpalac36/Testing-Internship/commit/912f720ac3986c0477b27a982666e83dd7a75e77
