### ISSUE TITLE
there is no need to introduce the variable. you can pass the value from resource file where you assert the url

### ISSUE THREAD

**Issue by ramonaZmole** [pitpalac36/Testing-Internship#12]
https://github.com/pitpalac36/Testing-Internship/blob/bc1d4f455f8334de374fe623cf04de835f8db7c0/Madison/Tests/TestCart.cs#L68

**Comment by horgaemilia** [comment]
https://github.com/pitpalac36/Testing-Internship/commit/c1db4a46da92bf755a78c75cb03c725861d3928a
