### ISSUE TITLE
The showroom is not very intuitive, if it is related to the product details page then you can move the selectors to that page and the methods related to them there.

### ISSUE THREAD

**Issue by horgaemilia** [pitpalac36/Testing-Internship#130]
https://github.com/pitpalac36/Testing-Internship/blob/be433a165868cb771a4028d22d5610f15c4cde1d/Madison/Pages/MyWishlistPage.cs#L7

**Comment by pitpalac36** [comment]
https://github.com/pitpalac36/Testing-Internship/commit/957e550e1d59cb03a8a7614238da8142391e0c08
