### ISSUE TITLE
The get url function is suitable for all pages and not specific to the wishlist, i think that it can be moved to the Pages class

### ISSUE THREAD

**Issue by horgaemilia** [pitpalac36/Testing-Internship#131]
https://github.com/pitpalac36/Testing-Internship/blob/5142f92ea31902346c6184cbb12ba391c99f1da6/Madison/Pages/MyWishlistPage.cs#L66

**Comment by pitpalac36** [comment]
https://github.com/pitpalac36/Testing-Internship/commit/785dee73f7369e1dba5f0056f3f50e9f51b9cfc3
