### ISSUE TITLE
This name is a bit confusing.. maybe ContinueShoppingVisibleWhenCartEmptyTest?

### ISSUE THREAD

**Issue by pitpalac36** [pitpalac36/Testing-Internship#145]
https://github.com/pitpalac36/Testing-Internship/blob/5142f92ea31902346c6184cbb12ba391c99f1da6/Madison/Tests/TestCart.cs#L30

**Comment by horgaemilia** [comment]
https://github.com/pitpalac36/Testing-Internship/commit/bdd6713b2f5fc69d0b24ce08c0d2db76f2b2ec07
