### ISSUE TITLE
Browser.webDriver.Url is used twice in this method and could be used more in the future. Maybe a utils getter would be nice

### ISSUE THREAD

**Issue by pitpalac36** [pitpalac36/Testing-Internship#146]
https://github.com/pitpalac36/Testing-Internship/blob/5142f92ea31902346c6184cbb12ba391c99f1da6/Madison/Tests/TestCart.cs#L51

**Comment by horgaemilia** [comment]
https://github.com/pitpalac36/Testing-Internship/commit/aa8db1be366a21eab9a4ed8969f704d8aa1e7b99
