### ISSUE TITLE
you don't need the extra variable, you can write Pages.ProductsPage.GetErrorListSelector().Count.Should().Be(errorCountBefore.ConvertStringToInt32())

### ISSUE THREAD

**Issue by horgaemilia** [pitpalac36/Testing-Internship#151]
https://github.com/pitpalac36/Testing-Internship/blob/5142f92ea31902346c6184cbb12ba391c99f1da6/Madison/Tests/ProductTests.cs#L160

**Comment by meOtniel** [comment]
solved, please recheck
