### ISSUE TITLE
the size variable is unused

### ISSUE THREAD

**Issue by horgaemilia** [pitpalac36/Testing-Internship#152]
https://github.com/pitpalac36/Testing-Internship/blob/5142f92ea31902346c6184cbb12ba391c99f1da6/Madison/Tests/ProductTests.cs#L164

**Comment by pitpalac36** [comment]
https://github.com/pitpalac36/Testing-Internship/commit/2aaa295a4f6d723dee0661a76751963c19ebbfe0
