### ISSUE TITLE
You do not need the extra variable, you can write the assert on a single line

### ISSUE THREAD

**Issue by horgaemilia** [pitpalac36/Testing-Internship#153]
https://github.com/pitpalac36/Testing-Internship/blob/5142f92ea31902346c6184cbb12ba391c99f1da6/Madison/Tests/ProductTests.cs#L166

**Comment by horgaemilia** [comment]
Same as issue https://github.com/pitpalac36/Testing-Internship/issues/151

**Comment by meOtniel** [comment]
done, please retest
