### ISSUE TITLE
Test methods should contain the name test in their declaration

### ISSUE THREAD

**Issue by horgaemilia** [pitpalac36/Testing-Internship#160]
https://github.com/pitpalac36/Testing-Internship/blob/5142f92ea31902346c6184cbb12ba391c99f1da6/Madison/Tests/TestWishlist.cs#L29

**Comment by pitpalac36** [comment]
https://github.com/pitpalac36/Testing-Internship/commit/5dd2e8c3c6e732030091d859ef4a048fb0c16e22
