### ISSUE TITLE
I can't find the method-specific selector

### ISSUE THREAD

**Issue by clauu-mara** [pitpalac36/Testing-Internship#172]
https://github.com/pitpalac36/Testing-Internship/blob/5142f92ea31902346c6184cbb12ba391c99f1da6/Madison/Tests/ProductTests.cs#L113

**Comment by clauu-mara** [comment]
update: I found the selector, but I think you skipped a step, please resume

**Comment by meOtniel** [comment]
improvement for next sprint, wont fix for now
