### ISSUE TITLE
all the selectors must be declared as global in a class. you might add them duplicate if not.

### ISSUE THREAD

**Issue by ramonaZmole** [pitpalac36/Testing-Internship#20]
https://github.com/pitpalac36/Testing-Internship/blob/bc1d4f455f8334de374fe623cf04de835f8db7c0/Madison/Pages/MyCartPage.cs#L33

**Comment by horgaemilia** [comment]
https://github.com/pitpalac36/Testing-Internship/commit/5acc60021fbadee70b0cb489960e766ef9f5453c
