### ISSUE TITLE
there is no need to introduce a variable here. you can just say Pages.HomePage.checkIfHomeMainImageIsVisible().Should().BeTrue();       

### ISSUE THREAD

**Issue by ramonaZmole** [pitpalac36/Testing-Internship#22]
https://github.com/pitpalac36/Testing-Internship/blob/bc1d4f455f8334de374fe623cf04de835f8db7c0/Madison/Tests/ProductTests.cs#L32

**Comment by meOtniel** [comment]
solved, please recheck
