### ISSUE TITLE
instead of returning the valued inserted you can add a parameter and send the value that you want from test

### ISSUE THREAD

**Issue by ramonaZmole** [pitpalac36/Testing-Internship#26]
https://github.com/pitpalac36/Testing-Internship/blob/bc1d4f455f8334de374fe623cf04de835f8db7c0/Madison/Tests/TestWishlist.cs#L46

**Comment by pitpalac36** [comment]
https://github.com/pitpalac36/Testing-Internship/commit/28485acfdd79f29af2fe30b5020e9011f1c668b9
