### ISSUE TITLE
since we are using only string to pass most of the values. you don't really need to have int parameter if you have to convert it after

### ISSUE THREAD

**Issue by ramonaZmole** [pitpalac36/Testing-Internship#37]
https://github.com/pitpalac36/Testing-Internship/blob/45de432d7a6429012d7d07d9a8601a03b638532d/Madison/Pages/MyWishlistPage.cs#L45

**Comment by pitpalac36** [comment]
solved this yesterday 
https://github.com/pitpalac36/Testing-Internship/commit/292ab17e4b55946a2bbdc3682a0db697b062449a
