### ISSUE TITLE
there is not need for a variable here

### ISSUE THREAD

**Issue by ramonaZmole** [pitpalac36/Testing-Internship#39]
https://github.com/pitpalac36/Testing-Internship/blob/45de432d7a6429012d7d07d9a8601a03b638532d/Madison/Tests/TestCart.cs#L39

**Comment by ramonaZmole** [comment]
IsItemTableVisile().Should().BeFalse();

**Comment by horgaemilia** [comment]
https://github.com/pitpalac36/Testing-Internship/commit/b3b434d05a71df583dd76afd1fec746b1584a5d8
