### ISSUE TITLE
I think this selector can be improved. We cannot rely on the fact that the button will remain the third one in the buttons list

### ISSUE THREAD

**Issue by tudorsilvan** [pitpalac36/Testing-Internship#51]
https://github.com/pitpalac36/Testing-Internship/blob/a21907fc89c4fae12ef3212b1e3df96465ad9b8a/Madison/Pages/MyCartPage.cs#L21

**Comment by horgaemilia** [comment]
https://github.com/pitpalac36/Testing-Internship/commit/a734845edb56f20f9140a7bf60223f006ff1a2f6
