### ISSUE TITLE
This method can be parameterized. This way we can add different items to cart

### ISSUE THREAD

**Issue by tudorsilvan** [pitpalac36/Testing-Internship#52]
https://github.com/pitpalac36/Testing-Internship/blob/a21907fc89c4fae12ef3212b1e3df96465ad9b8a/Madison/Pages/MyCartPage.cs#L36

**Comment by horgaemilia** [comment]
https://github.com/pitpalac36/Testing-Internship/commit/c1db4a46da92bf755a78c75cb03c725861d3928a
