### ISSUE TITLE
this method is kind of useless. you can directly call in test Browser.goto method

### ISSUE THREAD

**Issue by ramonaZmole** [pitpalac36/Testing-Internship#64]
https://github.com/pitpalac36/Testing-Internship/blob/628d8ee43af5bc926316d36f2547f8f0cde8d946/Madison/Pages/MyCartPage.cs#L86

**Comment by horgaemilia** [comment]
https://github.com/pitpalac36/Testing-Internship/commit/001491ccc8fd8d46f60a1f4678a8ea860441cc61
