### ISSUE TITLE
the name is not very suggestive. you can change it to InsertQuantity(string quantity)

### ISSUE THREAD

**Issue by ramonaZmole** [pitpalac36/Testing-Internship#65]
https://github.com/pitpalac36/Testing-Internship/blob/628d8ee43af5bc926316d36f2547f8f0cde8d946/Madison/Pages/MyCartPage.cs#L60

**Comment by horgaemilia** [comment]
https://github.com/pitpalac36/Testing-Internship/commit/7a2aadfee675b5fd899fc01b0f192b4b611fea17
