### ISSUE TITLE
This can be renamed to GetQuantity

### ISSUE THREAD

**Issue by ramonaZmole** [pitpalac36/Testing-Internship#66]
https://github.com/pitpalac36/Testing-Internship/blob/628d8ee43af5bc926316d36f2547f8f0cde8d946/Madison/Pages/MyCartPage.cs#L66

**Comment by horgaemilia** [comment]
https://github.com/pitpalac36/Testing-Internship/commit/7a2aadfee675b5fd899fc01b0f192b4b611fea17
