### ISSUE TITLE
Not a good name. This should be something like IsCartLabelPresent(). also the label is not very suggestive. that lable is actually cart quantity. and it's on homepage. this selectos and method should be moved on homepage

### ISSUE THREAD

**Issue by ramonaZmole** [pitpalac36/Testing-Internship#67]
https://github.com/pitpalac36/Testing-Internship/blob/628d8ee43af5bc926316d36f2547f8f0cde8d946/Madison/Pages/MyCartPage.cs#L76

**Comment by horgaemilia** [comment]
https://github.com/pitpalac36/Testing-Internship/commit/7a511c1bcaff37bd75412357cb6fc5f8bb1eb257
