### ISSUE TITLE
tests should not contain this kind of logic. everything should be hidden in methods from pages. think of other way how you can insert the qty in cart

### ISSUE THREAD

**Issue by ramonaZmole** [pitpalac36/Testing-Internship#72]
https://github.com/pitpalac36/Testing-Internship/blob/244b8254fa9ebd3b3b5beda9423e2edc1b42cf84/Madison/Tests/TestCart.cs#L136

**Comment by horgaemilia** [comment]
https://github.com/pitpalac36/Testing-Internship/commit/58897af06c9f34fac9c1121b9642df5baf211632
