### ISSUE TITLE
the test name is not quite accurate. you basically want to check the functionality of updating the qty in cart

### ISSUE THREAD

**Issue by ramonaZmole** [pitpalac36/Testing-Internship#73]
https://github.com/pitpalac36/Testing-Internship/blob/244b8254fa9ebd3b3b5beda9423e2edc1b42cf84/Madison/Tests/TestCart.cs#L131

**Comment by horgaemilia** [comment]
https://github.com/pitpalac36/Testing-Internship/commit/dc3692e123b472187a0287b33c217c82d2bddd5f
