### ISSUE TITLE
How else can you insert the review and use only one method?

### ISSUE THREAD

**Issue by ramonaZmole** [pitpalac36/Testing-Internship#74]
https://github.com/pitpalac36/Testing-Internship/blob/244b8254fa9ebd3b3b5beda9423e2edc1b42cf84/Madison/Tests/ProductTests.cs#L132

**Comment by ramonaZmole** [comment]
also, the method names should be readable as a sentence. e.g. AddReview();

**Comment by meOtniel** [comment]
solved, please retest
