### ISSUE TITLE
this method can be replaces with SelectMyAccountMenu("")

### ISSUE THREAD

**Issue by ramonaZmole** [pitpalac36/Testing-Internship#75]
https://github.com/pitpalac36/Testing-Internship/blob/244b8254fa9ebd3b3b5beda9423e2edc1b42cf84/Madison/Tests/TestWishlist.cs#L27

**Comment by ramonaZmole** [comment]
also, the method should have been added in the hompege class because the menu to navigate to wishlist is on homepage

**Comment by pitpalac36** [comment]
https://github.com/pitpalac36/Testing-Internship/commit/6b02059e5fd26b73c47bb203804751f6c9087ca0
