### ISSUE TITLE
this method I think is duplicated with another one from Homepage. You can extract it into a separate helper class like Browser because you are getting the Url from the driver

### ISSUE THREAD

**Issue by ramonaZmole** [pitpalac36/Testing-Internship#78]
https://github.com/pitpalac36/Testing-Internship/blob/244b8254fa9ebd3b3b5beda9423e2edc1b42cf84/Madison/Tests/TestWishlist.cs#L78

**Comment by pitpalac36** [comment]
https://github.com/pitpalac36/Testing-Internship/commit/84c232e931a50c942af2727fdfcb766aa0ad6291
