### ISSUE TITLE
I am not really sure what this showroom is? is something from material details page? If yes you should reuse/move the methods into that page 

### ISSUE THREAD

**Issue by ramonaZmole** [pitpalac36/Testing-Internship#79]
https://github.com/pitpalac36/Testing-Internship/blob/14128b670bad081b4f1ecbdbae2d1d09f22a4030/Madison/Tests/TestWishlist.cs#L105

**Comment by pitpalac36** [comment]
https://github.com/pitpalac36/Testing-Internship/commit/957e550e1d59cb03a8a7614238da8142391e0c08
