### ISSUE TITLE
you can only specify UpdateWishlist. there is no need to say you have to click on it. 

### ISSUE THREAD

**Issue by ramonaZmole** [pitpalac36/Testing-Internship#8]
https://github.com/pitpalac36/Testing-Internship/blob/bc1d4f455f8334de374fe623cf04de835f8db7c0/Madison/Tests/TestWishlist.cs#L47

**Comment by pitpalac36** [comment]
https://github.com/pitpalac36/Testing-Internship/commit/5eafb514b6ea18564c4e07b340245553dd4dba2f
