### ISSUE TITLE
A few unused variables (Emilia pls don't be mad at me)

### ISSUE THREAD

**Issue by pitpalac36** [pitpalac36/Testing-Internship#97]
https://github.com/pitpalac36/Testing-Internship/blob/dc18beb111b0ab20d1bcf82a04a4c6a8e8024c2b/Madison/Pages/MyCartPage.cs#L22

**Comment by horgaemilia** [comment]
https://github.com/pitpalac36/Testing-Internship/commit/1027f8786da3421f3d28ed1b96bc41d2730b7d22
