### ISSUE TITLE
The name is not very intuitive

### ISSUE THREAD

**Issue by horgaemilia** [pitpalac36/Testing-Internship#98]
https://github.com/pitpalac36/Testing-Internship/blob/dc18beb111b0ab20d1bcf82a04a4c6a8e8024c2b/Madison/Pages/MyWishlistPage.cs#L15

**Comment by pitpalac36** [comment]
https://github.com/pitpalac36/Testing-Internship/commit/f1395c8cd41f543ce6efd7fbbce50d08a063c8bc
