### ISSUE TITLE
All selectors contain button, field etc in their names except this one

### ISSUE THREAD

**Issue by pitpalac36** [pitpalac36/Testing-Internship#99]
https://github.com/pitpalac36/Testing-Internship/blob/dc18beb111b0ab20d1bcf82a04a4c6a8e8024c2b/Madison/Pages/MyCartPage.cs#L21

**Comment by horgaemilia** [comment]
https://github.com/pitpalac36/Testing-Internship/commit/2cbc16a20f4b577dac7c5fd9c02a5e0a276c1fb2
